"""
LangChain Agent Frontend Example: Generative UI Agent

This example demonstrates:
- Building an agent that generates UI specifications as JSON
- Using structured output to ensure valid component schemas
- Streaming UI generation for real-time updates
- Integration with React frontend via API

Generative UI Pattern:
1. Developer defines a component catalog (available components)
2. Agent generates JSON specs describing the UI tree
3. Frontend renders the specs using json-render or similar
4. Users see UI generated in real-time as the agent streams

This is a backend service that serves UI specs to a React frontend.
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from langchain.agents import create_agent
from langchain_ollama import ChatOllama
import json
from typing import Optional

# ============================================================================
# UI Component Catalog Definition
# ============================================================================
# This defines what components are available to the agent

COMPONENT_CATALOG = {
    "components": {
        "Card": {
            "description": "A card container with optional title and padding",
            "props": {
                "title": "string (optional)",
                "padding": "enum: sm|md|lg (optional)"
            }
        },
        "Stack": {
            "description": "A layout container that stacks children vertically or horizontally",
            "props": {
                "direction": "enum: vertical|horizontal (required)",
                "gap": "enum: sm|md|lg (optional)"
            }
        },
        "TextInput": {
            "description": "A text input field with optional label and placeholder",
            "props": {
                "label": "string (optional)",
                "placeholder": "string (optional)",
                "type": "enum: text|email|password|number|textarea (optional)"
            }
        },
        "Button": {
            "description": "A clickable button with label and style variants",
            "props": {
                "label": "string (required)",
                "variant": "enum: primary|secondary|ghost|link (optional)",
                "fullWidth": "boolean (optional)"
            }
        },
        "Text": {
            "description": "Display text content",
            "props": {
                "content": "string (required)",
                "size": "enum: sm|md|lg|xl (optional)"
            }
        },
        "Badge": {
            "description": "A small label or status indicator",
            "props": {
                "label": "string (required)",
                "variant": "enum: primary|success|warning|error (optional)"
            }
        },
        "Table": {
            "description": "Display tabular data",
            "props": {
                "columns": "string (required) - comma-separated column names",
                "title": "string (optional)"
            }
        }
    }
}


# ============================================================================
# UI Spec Schema
# ============================================================================
# This is what the agent generates

class UIElement(BaseModel):
    """A single UI element in the component tree"""
    type: str  # Component name (Card, Stack, TextInput, Button, etc.)
    props: dict  # Component-specific properties
    children: list[str] = []  # IDs of child elements


class UISpec(BaseModel):
    """Complete UI specification generated by the agent"""
    root: str  # ID of the root element
    elements: dict[str, UIElement]  # Map of element IDs to definitions


# ============================================================================
# Tool Definitions for the Agent
# ============================================================================

def generate_ui_spec(description: str) -> UISpec:
    """Generate a UI specification from a natural language description.
    
    This tool would typically use the catalog to guide the AI in
    generating valid component combinations.
    
    Args:
        description: Natural language description of desired UI
    
    Returns:
        A valid UISpec that can be rendered by the frontend
    """
    # For demonstration, return a sample UI spec
    # In production, this would use structured output from the LLM
    return UISpec(
        root="main-card",
        elements={
            "main-card": UIElement(
                type="Card",
                props={"title": "Weather App", "padding": "md"},
                children=["content-stack"]
            ),
            "content-stack": UIElement(
                type="Stack",
                props={"direction": "vertical", "gap": "md"},
                children=["city-input", "search-btn", "result-area"]
            ),
            "city-input": UIElement(
                type="TextInput",
                props={
                    "label": "Enter city name",
                    "placeholder": "e.g., New York, London",
                    "type": "text"
                },
                children=[]
            ),
            "search-btn": UIElement(
                type="Button",
                props={"label": "Get Weather", "variant": "primary", "fullWidth": True},
                children=[]
            ),
            "result-area": UIElement(
                type="Card",
                props={"title": "Weather Information", "padding": "sm"},
                children=["result-text"]
            ),
            "result-text": UIElement(
                type="Text",
                props={"content": "Weather will appear here...", "size": "md"},
                children=[]
            )
        }
    )


def get_weather(city: str) -> str:
    """Get weather for a city (tool for agent)"""
    return f"The weather in {city} is sunny with a temperature of 72°F."


def search_web(query: str) -> str:
    """Search the web (tool for agent)"""
    return f"Search results for '{query}': ..."


# ============================================================================
# FastAPI Application Setup
# ============================================================================

app = FastAPI(
    title="LangChain Generative UI Agent",
    description="Agent backend that generates UI specifications",
    version="1.0.0"
)

# Enable CORS for frontend development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================================
# API Endpoints
# ============================================================================

@app.get("/health")
def health_check():
    """Health check endpoint"""
    return {"status": "ok"}


@app.get("/catalog")
def get_catalog():
    """Get the component catalog available to the AI.
    
    The frontend can use this to understand what components
    the agent can generate.
    """
    return COMPONENT_CATALOG


@app.post("/generate-ui")
def generate_ui(request: dict):
    """Generate a UI specification from a description.
    
    Request body:
    {
        "description": "Create a login form"
    }
    
    Returns:
    A UISpec that the frontend can render
    """
    description = request.get("description", "")
    if not description:
        raise HTTPException(status_code=400, detail="Description required")
    
    # Generate UI spec using the agent
    # In a real implementation, this would use the LLM
    ui_spec = generate_ui_spec(description)
    
    return ui_spec.model_dump()


@app.post("/stream-ui")
def stream_ui(request: dict):
    """Stream UI specification generation (for real-time updates).
    
    This endpoint streams the UI spec as it's being generated,
    allowing the frontend to display UI components progressively.
    """
    description = request.get("description", "")
    if not description:
        raise HTTPException(status_code=400, detail="Description required")
    
    async def generate():
        """Generator that yields UI spec updates as JSON lines"""
        try:
            # Simulate progressive UI generation
            # In production, this would stream from the LLM
            
            # First, stream the root element
            yield 'data: {"event": "element_added", "element": {"id": "main-card", "type": "Card", "props": {"title": "Generated UI", "padding": "md"}}}\n\n'
            
            # Then stream child elements
            elements = [
                ('content-stack', 'Stack', '{"direction": "vertical", "gap": "md"}'),
                ('city-input', 'TextInput', '{"label": "Enter city", "placeholder": "City name"}'),
                ('search-btn', 'Button', '{"label": "Search", "variant": "primary"}'),
            ]
            
            for elem_id, elem_type, elem_props in elements:
                yield f'data: {{"event": "element_added", "element": {{"id": "{elem_id}", "type": "{elem_type}", "props": {elem_props}}}}}\n\n'
            
            # Finally, send the complete spec
            ui_spec = generate_ui_spec(description)
            yield f'data: {{"event": "complete", "spec": {json.dumps(ui_spec.model_dump())}}}\n\n'
            
        except Exception as e:
            yield f'data: {{"event": "error", "message": "{str(e)}"}}\n\n'
    
    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache"}
    )


@app.post("/agent/chat")
def agent_chat(request: dict):
    """Chat with the agent using natural language.
    
    The agent understands the UI component catalog and can
    generate appropriate UIs based on your description.
    
    Request body:
    {
        "message": "Create a form to collect user feedback"
    }
    
    Returns:
    {
        "response": "I've created a feedback form UI for you.",
        "ui_spec": { ... },
        "used_tools": ["generate_ui_spec"]
    }
    """
    message = request.get("message", "")
    if not message:
        raise HTTPException(status_code=400, detail="Message required")
    
    try:
        # Initialize the agent
        model = ChatOllama(model="qwen3.5:latest")
        
        # Define system prompt that includes catalog info
        system_prompt = f"""You are a helpful UI generation assistant.
        
You can generate UI specifications using these available components:
{json.dumps(COMPONENT_CATALOG['components'], indent=2)}

When asked to create a UI, use the generate_ui_spec tool.
Always consider the best components for the user's needs.

For example:
- For data display: use Table or Stack with Text
- For input: use TextInput, Button
- For containers: use Card, Stack
- For status: use Badge
"""
        
        agent = create_agent(
            model=model,
            tools=[generate_ui_spec, get_weather, search_web],
            system_prompt=system_prompt
        )
        
        # Invoke the agent
        result = agent.invoke({"messages": [{"role": "user", "content": message}]})
        
        # Extract the response
        last_message = result["messages"][-1]
        response_text = last_message.content if hasattr(last_message, 'content') else str(last_message)
        
        return {
            "response": response_text,
            "success": True,
            "message_count": len(result["messages"])
        }
    
    except Exception as e:
        return {
            "response": f"Error: {str(e)}",
            "success": False
        }


# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == "__main__":
    import uvicorn
    print("Starting Generative UI Agent Server...")
    print("Visit http://localhost:8000/docs for API documentation")
    uvicorn.run(app, host="0.0.0.0", port=8000)
