"""Message Objects Usage Example

Demonstrates using LangChain message objects (SystemMessage, HumanMessage, AIMessage)
for multi-turn conversations with full conversation history.
This approach is ideal when managing context across multiple exchanges.

Message Types:
- SystemMessage: Initial instructions that prime the model's behavior
- HumanMessage: Represents user input and interactions
- AIMessage: Responses generated by the model

Prerequisite: Ollama must be running with qwen model installed
"""
import pprint

from langchain.chat_models import init_chat_model
from langchain.messages import AIMessage, HumanMessage, SystemMessage

# Initialize the chat model using Ollama
model = init_chat_model("ollama:qwen3.5:latest")

# Alternative simple approach (commented out):
# sys_msg = SystemMessage(content="You are a helpful assistant that translates English to Tamil.")
# human_msg = HumanMessage(content="Translate: I love my mom and dad.")
# messages = [sys_msg, human_msg]

# Create a list of messages for multi-turn conversation
# This includes system instruction, user request, and prior AI response
messages = [
    SystemMessage("You are a poetry expert"),  # Set model behavior and role
    HumanMessage("Write a haiku about spring"),  # User request
    AIMessage("Cherry blossoms bloom...")  # Prior model response for context
]

# Invoke model with message list
response = model.invoke(messages)

# Print the AIMessage response object with all metadata
pprint.pprint(response)

print("✓ Message-based conversation completed.")